name: Doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Python Markdown Documentation
        uses: jbheard/markdown-docs@v0.1
        with:
          src_path: 'main'
          dst_path: 'docs'

      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.md"