name: testing
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install py2exe
      - name: build exe
        run: |
          py setup_exe.py py2exe
      - name: run exe
        run |
        dist/main.exe
        ^C
      - name: Pybuilder
        run: |
          pip install pybuilder
          pyb